# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - nbgitpuller
  - pip
  - pip:
      - otter-grader==4.3.2
      - datascience==0.17.6
      # Allow users to download their home directories
      - jupyter-tree-download
